version: '3'

services:
  docs:
    image: happychoices_local_docs
    container_name: happychoices_local_docs
    build:
      context: src/happychoices
      dockerfile: compose/local/docs/Dockerfile
    env_file:
      - .envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./happychoices:/app/happychoices:z
    ports:
      - '9000:9000'
    command: /start-docs
