FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Update and install system dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends gcc libpq-dev build-essential \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /src

# Install Python dependencies
COPY requirements.txt .
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt

# Install testing dependencies
RUN pip3 install --no-cache-dir pytest pytest-django

COPY ../src /src
COPY ../tests /tests

# Run the tests when the container starts
CMD ["pytest", "tests/"]